### ISSUE TITLE
try/catch does not restore prior set -e value

### ISSUE THREAD

**Issue by charles-dyfis-net** [niieani/bash-oo-framework#2]
...but rather forces `-e` to be unset when leaving a try block, regardless of its prior value.

**Comment by niieani** [comment]
Indeed, I thought about it. I left it like that on purpose, because you're not supposed to use the framework with ```-e``` set anyway (since that defeats the point of using error handling or try & catch). It's an easy fix though as it would only require capturing the flag first and setting it to the previous setting.
Feel free to file a pull request.

**Comment by niieani** [comment]
Solved with v2.0
